CREATE TABLE employee (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    emr_id    VARCHAR(50) NOT NULL UNIQUE,
    name      VARCHAR(50) NOT NULL,
    password  VARCHAR(255) NOT NULL,
    role      VARCHAR(20) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE reservation (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id BIGINT NOT NULL,
    reservation_date       DATE NOT NULL,
    reservation_time       TIME NOT NULL,
    reservation_status     VARCHAR(30) NOT NULL,
    treatment_status VARCHAR(30) NOT NULL,
    department VARCHAR(20) NOT NULL,
    chart_number  BIGINT NOT NULL,
    patient_name     VARCHAR(50) NOT NULL,
    direction  VARCHAR(20) NOT NULL,
    body_part  VARCHAR(30) NOT NULL,
    contrast_used  BOOLEAN,
    memo       VARCHAR(5000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL
);

ALTER TABLE RESERVATION ADD CONSTRAINT fk_reservation_employee FOREIGN KEY (employee_id) REFERENCES EMPLOYEE(id);
ALTER TABLE RESERVATION ADD CONSTRAINT uq_reservation_date_time UNIQUE (r_date, r_time);